Add comments for all builds

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -124,14 +124,16 @@ matrix:
     env: DOCKER=i386/debian:stretch PYTHON=3.5 CPP=14 GCC=6 INSTALL=1
     script:
       - |
+        # Consolidated 32-bit Docker Build + Install
         set -ex
-        $SCRIPT_RUN_PREFIX sh -c "set -e
-        cmake ${CMAKE_EXTRA_ARGS} -DPYBIND11_INSTALL=1 -DPYBIND11_TEST=0 .
-        make install
-        cp -a tests /pybind11-tests
-        mkdir /build-tests && cd /build-tests
-        cmake ../pybind11-tests ${CMAKE_EXTRA_ARGS} -DPYBIND11_WERROR=ON
-        make pytest -j 2"
+        $SCRIPT_RUN_PREFIX sh -c "
+          set -ex
+          cmake ${CMAKE_EXTRA_ARGS} -DPYBIND11_INSTALL=1 -DPYBIND11_TEST=0 .
+          make install
+          cp -a tests /pybind11-tests
+          mkdir /build-tests && cd /build-tests
+          cmake ../pybind11-tests ${CMAKE_EXTRA_ARGS} -DPYBIND11_WERROR=ON
+          make pytest -j 2"
         set +ex
 cache:
   directories:
@@ -237,6 +239,7 @@ install:
   set +ex
 script:
 - |
+  # CMake Configuration
   set -ex
   $SCRIPT_RUN_PREFIX cmake ${CMAKE_EXTRA_ARGS} \
     -DPYBIND11_PYTHON_VERSION=$PYTHON \
@@ -246,20 +249,24 @@ script:
     .
   set +ex
 - |
+  # pytest
   set -ex
   $SCRIPT_RUN_PREFIX make pytest -j 2 VERBOSE=1
   set +ex
 - |
+  # cpptest
   set -ex
   $SCRIPT_RUN_PREFIX make cpptest -j 2
   set +ex
 - |
+  # CMake Build Interface
   set -ex
   if [ -n "$CMAKE" ]; then $SCRIPT_RUN_PREFIX make test_cmake_build; fi
   set +ex
 after_failure: cat tests/test_cmake_build/*.log*
 after_script:
 - |
+  # Cleanup (Docker)
   set -ex
   if [ -n "$DOCKER" ]; then docker stop "$containerid"; docker rm "$containerid"; fi
   set +ex
